#ifndef _OPERATION_TYPE_H_
#define _OPERATION_TYPE_H_

enum operation_t {
    GUI,
    ENCODING_FILEIN_STDOUT,
    DECODING_FILEIN_STDOUT,
    ENCODING_STDIN_FILEOUT,
    DECODING_STDIN_FILEOUT,
    ENCODING_STDIO,
    DECODING_STDIO,
    ENCODING_FILE,
    DECODING_FILE,
    UNKNOWN,
    HELP
};

#endif